# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Sam Windell

version = 1
SPDX-PackageName = "Floe"
SPDX-PackageSupplier = "Sam Windell"
SPDX-PackageDownloadLocation = "https://github.com/floe-audio/Floe"

[[annotations]]
path = "test_files/**"
SPDX-FileCopyrightText = "2024 Sam Windell"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["website/static/package-database.json", "website/static/CNAME", "website/package-lock.json", "website/package.json", "website/versions.json", "website/versioned_sidebars/version-stable-sidebars.json"]
SPDX-FileCopyrightText = "2024-2025 Sam Windell"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["website/static/images/*"]
SPDX-FileCopyrightText = "2025 Sam Windell"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["**.lock", "build_resources/**.lock", "version.txt", ".github/FUNDING.yml"]
SPDX-FileCopyrightText = "2024 Sam Windell"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["build_resources/reverb_irs/**.flac"]
SPDX-FileCopyrightText = "2025 Sam Windell"
SPDX-License-Identifier = "CC0-1.0"
